package records;

public class StudentList {
    public static void main(String[] args) {
        Student s1 = new Student("John", 100, 5);
        Student s2 = new Student("Alex", 101, 5);
        Student s3 = new Student("Bill", 102, 5);

        // all values assigned using the constructors to a instance are final

        System.out.println(s1);
        System.out.println(s2);
        System.out.println(s3);

        System.out.println("----------------");

        // accessor methods generated by record (similar to getter methods)
        System.out.println(s1.name());
        System.out.println(s1.rollNum());
        System.out.println(s1.grade());

    }
}
